title: Fair-ML Conference Deadlines # (Maintained by @hcorinna)
description: Countdowns to fair-ML / AI ethics / computational social science conference deadlines
author: Corinna Hertweck

domain: "hcorinna.github.io"
baseurl: "/fair-deadlines"

github_username: hcorinna
github_repo: fair-deadlines

markdown: kramdown

include: ['_pages']